### PR TITLE
Fix dashboard error message display restrictions 

### LINKED ISSUE #330: Dashboard TestCase view error message view hides part of the message.
**Description:**
screenshot from 2018-01-10 12-23-39

Part of the message is hidden because of table row styles.

### PR DESCRIPTION
**Pull request by sameerawickramasekara**
## Purpose
Resolves #330 

## Goals
Change style of dashboard table to show the complete content of error message.

## Approach
Used CSS property `wordWrap:break-word`

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: web/src/main/react-dashboard/src/components/TestCaseView.js [hunk 1]
```diff
@@ -83,7 +83,10 @@ class TestCaseView extends Component {
                                 <TableRowColumn>
                                     <h4>{data.name}</h4></TableRowColumn>
                                 <TableRowColumn><SingleRecord value={data.success} /></TableRowColumn>
-                                <TableRowColumn style={{ color: 'red' }}>
+                                <TableRowColumn style={{
+                                    color: 'red', whiteSpace: 'normal',
```
Comment (vidurananayakkara) [inline web/src/main/react-dashboard/src/components/TestCaseView.js]: Shall we have `, whiteSpace: 'normal',` in a new line so that the style is consistent and more readable
