### PR TITLE
Change TestGrid dashboard structure

### LINKED ISSUE #334: Dashboard API response is not in expected format
**Description:**
Even though we expect the last build status for each day, the response contains multiple results for a single day. 

screenshot from 2018-01-10 20-01-23

### LINKED ISSUE #346: Dashboard Logs and Report link is not working
**Description:**
Dashboard links are not working on the PROD environment

### LINKED ISSUE #349: Intermittent HTTP 500 error from webapp.
**Description:**
HTTP 500 error occurs intermittently from the webapp when accessing APIs. 
Please find the log below.

**Affected Product Version:**

**Steps to reproduce:**
Deploy the war file in tomcat server and test APIs.

Log:

> Type Exception Report
> 
> Message org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
> 
> Description The server encountered an unexpected condition that prevented it from fulfilling the request.
> 
> xception
> 
> javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
> 	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:421)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> Root Cause
> 
> org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
> 	org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:256)
> 	org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:238)
> 	org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:483)
> 	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:313)
> 	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
> 	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
> 	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
> 	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
> 	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
> 	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> Root Cause
> 
> java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
> 	com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.findNameForDeserialization(JaxbAnnotationIntrospector.java:875)
> 	com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForDeserialization(AnnotationIntrospectorPair.java:749)
> 	com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addSetterMethod(POJOPropertiesCollector.java:618)
> 	com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:533)
> 	com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:309)
> 	com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
> 	com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
> 	com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
> 	com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
> 	com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:329)
> 	com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:313)
> 	com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
> 	com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:256)
> 	com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:179)
> 	com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
> 	com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
> 	com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
> 	com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
> 	com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
> 	com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
> 	com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1935)
> 	com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:677)
> 	com.fasterxml.jackson.databind.ObjectReader.withType(ObjectReader.java:718)
> 	com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:771)
> 	org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:260)
> 	org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
> 	org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
> 	org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74)
> 	org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
> 	org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
> 	org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
> 	org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:270)
> 	org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96)
> 	org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:81)
> 	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:125)
> 	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158)
> 	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
> 	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
> 	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
> 	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
> 	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
> 	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
> 	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> 	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
> 	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
> 	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
> 	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
> 	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
> 	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

### PR DESCRIPTION
**Pull request by sameerawickramasekara**
## Purpose

Resolves #334
Resolves #346 
Resolves #349 
 

## Goals
Change the existing dashboard and the related API

## Approach
Implement new API endpoints and React views to match the requirements

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java [hunk 1]
```diff
@@ -133,4 +134,91 @@ public TestPlan findByPrimaryKey(String id) throws TestGridDAOException {
...
+
+    /**
+     * This method returns the last failed {@link TestPlan} for a given product.
+     *
+     * @param product A Product object being queried.
+     * @return instance of a {@link TestPlan} representing the last failed test plan.
+     * @throws TestGridDAOException when an error occurs while executing the native sql query.
+     */
+    public TestPlan getLastFailure(Product product) throws TestGridDAOException {
+        String sql = "SELECT  t.* from test_plan t INNER JOIN (SELECT tp.infra_parameters," +
```
Comment (kasunbg) [inline dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java]: Shall we use `PrepardStatement`s instead?

File: dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java [hunk 2]
```diff
@@ -133,4 +134,91 @@ public TestPlan findByPrimaryKey(String id) throws TestGridDAOException {
...
+                "max(tp.modified_timestamp) AS time, dp.name FROM test_plan tp INNER JOIN " +
+                "deployment_pattern dp ON tp.DEPLOYMENTPATTERN_id=dp.id AND tp.status='FAIL' " +
+                "AND  tp.DEPLOYMENTPATTERN_id IN (SELECT id FROM deployment_pattern WHERE " +
+                "PRODUCT_id='" + product.getId() + "') GROUP BY tp.infra_parameters,dp.name) AS x ON " +
+                "t.infra_parameters=x.infra_parameters AND t.modified_timestamp=x.time ORDER BY time DESC LIMIT 1";
+        try {
+            return (TestPlan) entityManager.createNativeQuery(sql, TestPlan.class).getSingleResult();
+        } catch (Exception e) {
```
Comment (kasunbg) [inline dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java]: We usually put the try block for the entire logic, not just for the line where the exception is thrown.

And, shall we catch a specific exception here instead of Exception?

File: dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java [hunk 3]
```diff
@@ -133,4 +134,91 @@ public TestPlan findByPrimaryKey(String id) throws TestGridDAOException {
...
+     * @throws TestGridDAOException when an error occurs while executing the native query
+     */
+    public TestPlan getLastFailure(TestPlan testPlan) throws TestGridDAOException {
+        String sql = "select * from test_plan where infra_parameters='" + testPlan.getInfraParameters() +
+                "' AND DEPLOYMENTPATTERN_id='"
+                + testPlan.getDeploymentPattern().getId() + "'" +
+                " AND status='FAIL' order by modified_timestamp desc limit 1";
+        try {
+            return (TestPlan) entityManager.createNativeQuery(sql, TestPlan.class).getSingleResult();
+        } catch (Exception e) {
```
Comment (kasunbg) [inline dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java]: same as above. Please fix in all places...

File: web/src/main/java/org/wso2/testgrid/web/bean/TestPlan.java [hunk 4]
```diff
@@ -157,4 +160,46 @@ public String getLogLocation() {
...
     }
+
+    /**
+     * Returns the create timestamp for this test-plan.
+     *
+     * @return create timestamp for this test-plan
+     */
+    public Timestamp getCreatedTimestamp() {
+
+        return createdTimestamp == null ? null : (Timestamp) createdTimestamp.clone();
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/bean/TestPlan.java]: Good code..

File: web/src/main/react-dashboard/src/components/DeploymentPatternView.js [hunk 5]
```diff
@@ -63,33 +62,78 @@ class DeploymentPatternView extends Component {
     this.props.history.push(route);
   }
 
+
   render() {
     console.log(this.state);
+    var x = {};
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/DeploymentPatternView.js]: Shall we name the variable properly? 

Console.log should not be in production - https://stapp.space/how-to-remove-javascript-console-log-pros-2/

File: web/src/main/react-dashboard/src/components/DeploymentPatternView.js [hunk 6]
```diff
@@ -63,33 +62,78 @@ class DeploymentPatternView extends Component {
...
+                        <TableRowColumn rowSpan={x[key].length}>{key}</TableRowColumn>
+                        <TableRowColumn style={{ whiteSpace: 'normal', wordWrap: 'break-word' }}>{value.lastBuild.infraParams}</TableRowColumn>
+                        <TableRowColumn ><SingleRecord value={value.lastBuild.status}
+                          nevigate={() => this.nevigateToRoute("/testgrid/v0.9/", {
+                            testPlanId: value.lastBuild.id,
+                            testPlanInfra: value.lastBuild.infraParams,
+                          })} time={Moment(value.lastBuild.modifiedTimestamp).fromNow()}
+                        /> </TableRowColumn>
+                        <TableRowColumn ><SingleRecord value={value.lastFailed.status}
+                          nevigate={() => this.nevigateToRoute("/testgrid/v0.9/", {
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/DeploymentPatternView.js]: shall we create a constant for `/testgrid/v0.9/`?

File: web/src/main/react-dashboard/src/components/DeploymentPatternView.js [hunk 7]
```diff
@@ -63,33 +62,78 @@ class DeploymentPatternView extends Component {
...
+                    )
+                  } else {
+                    return (
 
-                /></TableRowColumn>
-              </TableRow>)
+                      <TableRow>
+                        <TableRowColumn >{value.lastBuild.infraParams}</TableRowColumn>
+                        <TableRowColumn ><SingleRecord value={value.lastBuild.status}
+                          nevigate={() => this.nevigateToRoute("/testgrid/v0.9/", {
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/DeploymentPatternView.js]: typo - *navigateToRoute

File: web/src/main/react-dashboard/src/components/ProductStatusView.js [hunk 8]
```diff
@@ -27,82 +27,78 @@ import {
...
+        /></TableRowColumn>
+        <TableRowColumn>
+          <h4 onClick={() => this.nevigateToRoute("/testgrid/v0.9/deployments/product/" + product.id, {
+            productId: product.id,
+            productName: product.name,
+          })} style={{ cursor: 'pointer', textDecoration: 'underline' }} >{Moment(product.lastfailed.modifiedTimestamp).fromNow()} </h4>
+        </TableRowColumn>
+        <TableRowColumn> <img src={require('../play.png')} width="48" height="48" /></TableRowColumn>
+        <TableRowColumn ><img src={require('../configure.png')} width="36" height="36" style={{ cursor: 'pointer' }}
+          onClick={() => { window.location = 'https://testgrid-live-dev.private.wso2.com/job/wso2is-5.4.0/job/01-single-node-deployment-pattern/configure' }} />
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/ProductStatusView.js]: hard-coding is ok to do for today's release - but this logic will fail in production! How about the following:

window.location = '/job/wso2is-5.4.0/job/01-single-node-deployment-pattern/configure'

File: dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java (hunk 1 above)
Comment (sameerawickramasekara) [reply dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java]: Used parameters instead preparedStatements

File: web/src/main/react-dashboard/src/components/ProductStatusView.js [hunk 9]
```diff
@@ -27,82 +27,78 @@ import {
...
-          })}
-          /></TableRowColumn>);
-        })}
-      </TableRow>);
-    })
+        <TableRowColumn> <img src={require('../close.png')} width="40" height="40" /></TableRowColumn>
+        <TableRowColumn ><h2 style={{ cursor: 'pointer' }} onClick={() => this.nevigateToRoute("/testgrid/v0.9/deployments/product/" + product.id, {
+          productId: product.id,
+          productName: product.name,
+        })}><i>{product.name}</i></h2></TableRowColumn>
```
[the remark this answers is not in the document]
Comment (sameerawickramasekara) [reply web/src/main/react-dashboard/src/components/ProductStatusView.js]: This step defines what to store in the app state to be used by next views,
so it saves the clicked productId, and productName

[the remark this answers is not in the document]
Comment (kasunbg) [reply web/src/main/react-dashboard/src/components/ProductStatusView.js]: OK.. I mean overall we have to change this to testPlanName.. not a blocker for this pr.. :)

File: web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java [hunk 10]
```diff
@@ -0,0 +1,183 @@
...
+     * Returns the last failed TestPlan of the product.
+     *
+     * @return {@link TestPlan} for last failed build
+     */
+    public TestPlan getLastfailed() {
+        return lastfailed;
+    }
+
+    /**
+     *Sets the last failed build for the product
```
Comment (harshanL) [inline web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java]: Fix the formatting issue in the comment.

File: web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java [hunk 11]
```diff
@@ -0,0 +1,183 @@
...
+     *
+     * @param lastfailed {@link TestPlan} for last failed build
+     */
+    public void setLastfailed(TestPlan lastfailed) {
+        this.lastfailed = lastfailed;
+    }
+
+    /**
+     *Returns the executable link for the product that contains all the jobs.
```
Comment (harshanL) [inline web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java]: Fix the formatting issue in the comment.

File: web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java [hunk 12]
```diff
@@ -0,0 +1,183 @@
...
+     *
+     * @return executable URL for the product
+     */
+    public String getExecuteLink() {
+        return executeLink;
+    }
+
+    /**
+     *Set the executable link for the product.
```
Comment (harshanL) [inline web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java]: Fix the formatting issue in the comment.

File: web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java [hunk 13]
```diff
@@ -0,0 +1,183 @@
...
+     * Returns the Configuration link for the product jobs in Jenkins
+     *
+     * @return the URL for configuration console
+     */
+    public String getConfigLink() {
+        return configLink;
+    }
+
+    /**
+     *Set the Jenkins configuration link for the product.
```
Comment (harshanL) [inline web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java]: Fix the formatting issue in the comment.
